server:
  port: 8081

spring:
  security:
    apiKey: ${AUTH_SERVICE_API_KEY:seu-api-key-aqui}
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/novalocacoes
    username: root
    password: 281004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  private-key: classpath:privateKey.pem
  public-key: classpath:publicKey.pem
  expiracao-segundos: ${AUTH_JWT_TEMPO_EXPIRACAO:3600}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    disable-swagger-default-url: true
  show-actuator: true