# Configurações comuns para todos os perfis
spring:
  application:
    name: auth-service
  security:
    apiKey: ${AUTH_SERVICE_API_KEY:seu-api-key-aqui}
  mail:
    host: smtp.gmail.com
    port: 587
    username: filipefranca876@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  private-key: classpath:privateKey.pem
  public-key: classpath:publicKey.pem
  expiracao-segundos: ${AUTH_JWT_TEMPO_EXPIRACAO:3600}

springdoc:
  show-actuator: false
  swagger-ui:
    path: /swagger-ui.html
    url: /auth/v3/api-docs
    config-url: /auth/v3/api-docs/swagger-config
    urls[0].url: /auth/v3/api-docs
    urls[0].name: API Docs
  api-docs:
    path: /v3/api-docs

---
# Perfil de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/novalocacoes
    username: root
    password: 281004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081
  id: localhost

admin:
  email: admin@infinitysolutions.com
  senha: admin123
  usuario-id: 00000000-0000-0000-0000-000000000001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

---
# Perfil de Produção
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:novalocacoes}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:281004}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT:8081}
  id: ${SERVER_ID:localhost}

admin:
  email: ${ADMIN_EMAIL:admin@infinitysolutions.com}
  senha: ${ADMIN_SENHA:admin123}
  usuario-id: 00000000-0000-0000-0000-000000000001

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_IP:localhost}:8761/eureka
    register-with-eureka: true
    fetch-registry: true