services:
  application_service:
    build:
      context: ./application-service
      dockerfile: Dockerfile
    container_name: application-service
    ports:
      - "8080:8082"
    environment:
      DB_HOST: db_service
      DB_PORT: 3306
      DB_NAME: novalocacoes
      DB_USERNAME: root
      DB_PASSWORD: 281004
      GMAIL_PASSWORD: gmail-password
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_ENDPOINT: http://localstack:4566
      AWS_S3_PUBLIC_BUCKET: arquivos-publicos-dev
      AWS_S3_PRIVATE_BUCKET: arquivos-privados-dev
      AWS_USE_LOCALSTACK: true
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - db_service
      - localstack
    networks:
      - novalocacoes-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db_service:
    image: mysql:8.0
    container_name: novalocacoes-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 281004
      MYSQL_DATABASE: novalocacoes
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bd_script.sql:/docker-entrypoint-initdb.d/1-schema.sql
    networks:
      - novalocacoes-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  novalocacoes-network:
    driver: bridge

volumes:
  mysql-data:
  localstack-data:
