server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]': # Aplica a todas as rotas
#            allowedOrigins: "*"  # Permite todas as origens
#            allowedMethods: # Metodos HTTP permitidos
#             - GET
#             - POST
#              - PUT
#              - DELETE
#              - PATCH
#              - OPTIONS
#              - HEAD
#            allowedHeaders: "*"  # Permite todos os headers
#            exposedHeaders: # Headers expostos ao cliente
#             - Authorization
#             - Content-Type
#            allowCredentials: false  # Nao permite credenciais (incompativel com "*")
#            maxAge: 3600  # Cache de preflight por 1 hora (em segundos)
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:   -- configurar depois com os projetos criados.
#        - id: login-service
#          uri: lb://login-service
#          predicates:
#            - Path=/api/**
#            - Method=*


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true